# URL pure, sans user:password
spring.datasource.url=jdbc:postgresql://dpg-d8ksup3tqb8s73ah78ng-a.oregon-postgres.render.com:5432/proclinic_db

# Les credentials doivent être sur leurs lignes dédiées
spring.datasource.username=proclinic_db_user
spring.datasource.password=aCTq1Qt6Qshd30ZagRd7MaXKupFOaXng

# Le dialecte pour PostgreSQL
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Optionnel : pour voir ce qui se passe lors de la connexion
spring.jpa.show-sql=false


#spring.application.name=proclinic

#spring.datasource.url=jdbc:postgresql://localhost:5432/proclinic_db
#spring.datasource.username=postgres
#spring.datasource.password=postgres

#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true

#spring.jpa.properties.hibernate.format_sql=true